# Simplified pre-commit configuration aligned with CI
repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Go linting - matches CI exactly
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.8
    hooks:
      - id: golangci-lint-full
        args: ['--timeout=5m', '--fix']

  # Go tests - simplified to match CI
  - repo: local
    hooks:
      - id: go-test
        name: Go Tests
        entry: go test -race ./...
        language: system
        pass_filenames: false

      - id: go-vet
        name: Go Vet
        entry: go vet ./...
        language: system
        pass_filenames: false
